FROM renciorg/renci-python-image:v0.0.1

# Add image info
LABEL org.opencontainers.image.source /github.com/TranslatorSRI/answer-appraiser

# set up requirements
WORKDIR /app

# Normal requirements
ADD requirements-lock.txt .
RUN pip install -r requirements-lock.txt

# Test requirements
ADD requirements-test-lock.txt .
RUN pip install -r requirements-test-lock.txt

# Copy in files
ADD . .

# set up default command
CMD pytest
